import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { Character, GetCharacterResults } from "../types/types";
import imageLoader from "../imageLoader";
import Link from "next/link";

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Link href={`/contacts`}>
          <a>contacts</a>
        </Link>

        {characters.map((character) => {
          return (
            <li key={character.id}>
              <Link href={`/characters/${character.id}`}>
                <a>{character.name}</a>
              </Link>

              <Image
                src={character.image}
                width={300}
                unoptimized
                height={300}
                alt={character.name}
                loader={imageLoader}
              />
            </li>
          );
        })}
      </>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  const { data }: { data: GetCharacterResults } = await axios.get(
    "https://rickandmortyapi.com/api/character"
  );

  const { results, info } = data;
  return {
    props: {
      characters: results,
    },
  };
};
